USE ROLE DCM_ADMIN;
USE WAREHOUSE DCM_WH;

-- Drop ANALYTICS views
DROP VIEW IF EXISTS SUMMIT_DB_DEV.ANALYTICS.LOCATION_ACTIVITY;
DROP VIEW IF EXISTS SUMMIT_DB_DEV.ANALYTICS.ORDER_SUMMARY;
DROP VIEW IF EXISTS SUMMIT_DB_DEV.ANALYTICS.PACKAGE_TRACKING;
DROP VIEW IF EXISTS SUMMIT_DB_DEV.ANALYTICS.PACKAGE_HOPS;
DROP VIEW IF EXISTS SUMMIT_DB_DEV.ANALYTICS.FRAUD_DETECTION;

-- Drop Layer 2 dynamic tables (TRANSFORM analytic)
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_FRAUD_DETECTION;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_LOCATION_ACTIVITY;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_ORDER_SUMMARY;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_PACKAGE_TRACKING;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_PACKAGE_HOPS;

-- Drop Layer 1 dynamic tables (TRANSFORM clean)
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_CUSTOMERS;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_SHIPPING_PRODUCTS;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_LOCATIONS;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_ORDERS;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_ORDER_ITEMS;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_PAYMENTS;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_PACKAGES;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_TRACKING_EVENTS;
DROP DYNAMIC TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.DT_CLEAN_DELIVERIES;

-- Drop standalone tables (TRANSFORM)
DROP TABLE IF EXISTS SUMMIT_DB_DEV.TRANSFORM.FRAUD_DETECTION_RESULTS;

-- Truncate RAW tables (reverse dependency order)
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.DELIVERIES;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.TRACKING_EVENTS;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.PACKAGES;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.PAYMENTS;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.ORDER_ITEMS;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.ORDERS;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.LOCATIONS;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.SHIPPING_PRODUCTS;
TRUNCATE TABLE SUMMIT_DB_DEV.RAW.CUSTOMERS;

SHOW TABLES IN SUMMIT_DB_DEV.RAW;
SHOW TABLES IN SUMMIT_DB_DEV.TRANSFORM;
SHOW VIEWS IN SUMMIT_DB_DEV.ANALYTICS;
