-- =============================================================================
-- Configure a Git repository in Snowflake
-- Repo: https://github.com/...
-- =============================================================================

USE ROLE ACCOUNTADMIN;

CREATE SCHEMA IF NOT EXISTS "USER$<USERNAME>".SECRETS;

CREATE OR REPLACE SECRET "USER$<USERNAME>".SECRETS.SUMMIT_GIT_SECRET
  TYPE = password
  USERNAME = '<GITHUB_USERNAME>'
  PASSWORD = '<GITHUB_PAT>';

CREATE OR REPLACE API INTEGRATION SUMMIT_GIT_API_INTEGRATION
  API_PROVIDER = git_https_api
  API_ALLOWED_PREFIXES = ('https://github.com/...')
  ALLOWED_AUTHENTICATION_SECRETS = ("USER$<USERNAME>".SECRETS.SUMMIT_GIT_SECRET)
  ENABLED = TRUE;

GRANT USAGE ON INTEGRATION SUMMIT_GIT_API_INTEGRATION TO ROLE SUMMIT_ADMIN;
USE ROLE SUMMIT_ADMIN;
USE DATABASE SUMMIT_DB_DEV;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE GIT REPOSITORY SUMMIT_GIT_REPO
  API_INTEGRATION = SUMMIT_GIT_API_INTEGRATION
  GIT_CREDENTIALS = "USER$<USERNAME>".SECRETS.SUMMIT_GIT_SECRET
  ORIGIN = 'https://github.com/.../...';

ALTER GIT REPOSITORY SUMMIT_GIT_REPO FETCH;
