define table SUMMIT_DB{{env_suffix}}.RAW.CUSTOMERS (
    CUSTOMER_ID NUMBER,
    CUSTOMER_TYPE VARCHAR NOT NULL,
    FIRST_NAME VARCHAR,
    LAST_NAME VARCHAR,
    COMPANY_NAME VARCHAR,
    TAX_ID VARCHAR,
    EMAIL VARCHAR NOT NULL,
    PHONE VARCHAR,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    POSTAL_CODE VARCHAR,
    COUNTRY VARCHAR,
    PREFERRED_LANGUAGE VARCHAR,
    ACCOUNT_STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.SHIPPING_PRODUCTS (
    PRODUCT_ID NUMBER,
    NAME VARCHAR NOT NULL,
    DESCRIPTION VARCHAR,
    SERVICE_TYPE VARCHAR NOT NULL,
    MAX_WEIGHT_KG NUMBER(10,2),
    MAX_LENGTH_CM NUMBER(10,2),
    MAX_WIDTH_CM NUMBER(10,2),
    MAX_HEIGHT_CM NUMBER(10,2),
    ZONE VARCHAR NOT NULL,
    BASE_PRICE NUMBER(10,2) NOT NULL,
    PRICE_PER_KG NUMBER(10,2),
    ESTIMATED_DAYS_MIN NUMBER,
    ESTIMATED_DAYS_MAX NUMBER,
    INSURANCE_INCLUDED BOOLEAN,
    SIGNATURE_REQUIRED BOOLEAN,
    ACTIVE BOOLEAN
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.LOCATIONS (
    LOCATION_ID NUMBER,
    NAME VARCHAR NOT NULL,
    TYPE VARCHAR NOT NULL,
    ADDRESS VARCHAR,
    CITY VARCHAR,
    COUNTRY VARCHAR,
    LATITUDE NUMBER(10,7),
    LONGITUDE NUMBER(10,7),
    CAPACITY NUMBER,
    OPERATING_HOURS VARCHAR,
    ACTIVE BOOLEAN
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.ORDERS (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER NOT NULL,
    ORDER_DATE TIMESTAMP_NTZ,
    STATUS VARCHAR,
    ORIGIN_LOCATION_ID NUMBER,
    PICKUP_ADDRESS VARCHAR,
    PICKUP_CITY VARCHAR,
    PICKUP_COUNTRY VARCHAR,
    DESTINATION_ADDRESS VARCHAR,
    DESTINATION_CITY VARCHAR,
    DESTINATION_COUNTRY VARCHAR,
    ESTIMATED_DELIVERY_DATE DATE,
    TOTAL_AMOUNT NUMBER(10,2),
    CURRENCY VARCHAR
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.ORDER_ITEMS (
    ORDER_ITEM_ID NUMBER,
    ORDER_ID NUMBER NOT NULL,
    PRODUCT_ID NUMBER NOT NULL,
    QUANTITY NUMBER NOT NULL,
    UNIT_PRICE NUMBER(10,2),
    DECLARED_WEIGHT_KG NUMBER(10,2),
    DECLARED_CONTENTS VARCHAR,
    DECLARED_VALUE NUMBER(10,2),
    INSURANCE_OPTED BOOLEAN
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.PAYMENTS (
    PAYMENT_ID NUMBER,
    ORDER_ID NUMBER NOT NULL,
    PAYMENT_METHOD VARCHAR NOT NULL,
    CARD_LAST_FOUR VARCHAR(4),
    CARD_BRAND VARCHAR,
    CARD_COUNTRY VARCHAR,
    BILLING_ADDRESS VARCHAR,
    BILLING_CITY VARCHAR,
    BILLING_COUNTRY VARCHAR,
    PAYMENT_AMOUNT NUMBER(10,2) NOT NULL,
    CURRENCY VARCHAR,
    PAYMENT_STATUS VARCHAR,
    PAYMENT_TIMESTAMP TIMESTAMP_NTZ,
    IP_ADDRESS VARCHAR,
    DEVICE_FINGERPRINT VARCHAR,
    TRANSACTION_REFERENCE VARCHAR
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.PACKAGES (
    PACKAGE_ID NUMBER,
    ORDER_ITEM_ID NUMBER NOT NULL,
    ORDER_ID NUMBER NOT NULL,
    TRACKING_NUMBER VARCHAR NOT NULL,
    ACTUAL_WEIGHT_KG NUMBER(10,2),
    LENGTH_CM NUMBER(10,2),
    WIDTH_CM NUMBER(10,2),
    HEIGHT_CM NUMBER(10,2),
    PACKAGE_TYPE VARCHAR,
    STATUS VARCHAR,
    CREATED_AT TIMESTAMP_NTZ
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.TRACKING_EVENTS (
    EVENT_ID NUMBER,
    PACKAGE_ID NUMBER NOT NULL,
    LOCATION_ID NUMBER,
    EVENT_TIMESTAMP TIMESTAMP_NTZ,
    EVENT_TYPE VARCHAR NOT NULL,
    STATUS VARCHAR,
    DESCRIPTION VARCHAR,
    CARRIER VARCHAR
)
change_tracking = TRUE;

define table SUMMIT_DB{{env_suffix}}.RAW.DELIVERIES (
    DELIVERY_ID NUMBER,
    PACKAGE_ID NUMBER NOT NULL,
    DRIVER_NAME VARCHAR,
    VEHICLE_ID VARCHAR,
    SCHEDULED_DATE DATE,
    ACTUAL_DELIVERY_DATE TIMESTAMP_NTZ,
    RECIPIENT_NAME VARCHAR,
    SIGNATURE_COLLECTED BOOLEAN,
    DELIVERY_NOTES VARCHAR,
    STATUS VARCHAR
)
change_tracking = TRUE;
